services:
  db:
    image: mariadb:10.4
    container_name: openeyes-db2
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openeyes
      MYSQL_USER: openeyes
      MYSQL_PASSWORD: openeyes
    # volumes:
    #   - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  openeyes:
    image: master1
    ports:
      - "8080:80"
    volumes:
      - ./db.conf:/etc/openeyes/db.conf
      - ./apache2.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    command: |
      sh -c '
      cd /var/www/openeyes/protected &&
      chmod +x yiic &&
      until mysql -h db -u root -proot openeyes -e "SELECT 1" > /dev/null 2>&1; do
        echo "Waiting for database connection..." &&
        sleep 5
      done &&
      /var/www/openeyes/protected/yiic migrate --all --interactive=0 || true &&
      /usr/sbin/apache2ctl -D FOREGROUND
      '
